services:
  backend:
    build: ./backend
    env_file:
      - ./.env.local
    container_name: mymap-backend
    ports:
      - "3001:3001"
    # environment:
    #   DB_HOST: ${DB_HOST}
    #   DB_PORT: ${DB_PORT}
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_NAME: ${DB_NAME}
    #   JWT_SECRET: ${JWT_SECRET}
    environment:
      NODE_ENV: production
    depends_on: []
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mymap-frontend
    ports:
      - "5173:3000"
    environment:
      VITE_API_URL: http://localhost:3001 # should match backend port
    depends_on:
      - backend
    restart: unless-stopped
