version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - ./.env.local
    container_name: mymap-backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: []
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mymap-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
